### ISSUE TITLE
empty error message

### ISSUE THREAD

**Issue by brnogz** [justinrainbow/json-schema#247]
i use 1.6.1 version of the library and when i try to run with my schema, it does not validate the schema and following log appears

> [Tue Mar 29 20:16:59.779195 2016] [:error] [pid 20422] [client 127.0.0.1:58380] [] NULL value found, but an object is required

**Comment by jojo1981** [comment]
@brnogz please add the schema you're using so when can try to reproduce this issue.

**Comment by brnogz** [comment]
sorry i forgot to add them 
schema file https://codeshare.io/h5KTF
example json file https://codeshare.io/5H3Fy

**Comment by jojo1981** [comment]
@brnogz The problem here has nothing to do with the schema or validation. The example json file doesn't contain a valid json string.

This is the fixed example json file:
    
    {
      "general": {
        "sef_enabled": 1
      },
      "controllers": [
        {
          "path": "index",
          "class": "HelloWorld"
        },
        {
          "path": "user",
          "class": "\\paxira\\controller\\User"
        }
      ],
      "database": {
        "database_type": "mysql",
        "database_name": "data",
        "server": "localhost",
        "username": "root",
        "password": "12",
        "charset": "utf8",
        "port": "3306",
        "prefix": "data_",
        "option": {
          "ATTR_CASE": "CASE_NATURAL"
        }
      }
    }
    
In the json string the backslash character needs to be escaped with a backslash character.
Check: http://www.json.org for more about escaping characters.

When this answer is sufficient please close this issue.

**Comment by jojo1981** [comment]
@brnogz Thanks for closing this issue!
