### ISSUE TITLE
State Which Version of Json Schma Spec

### ISSUE THREAD

**Issue by four43** [justinrainbow/json-schema#29]
Please state which version of the Json Schema spec is supported. Maybe create a supported feature list?

Thanks a lot for this project. It is a great and necessary component. I'm using Zend Framework 2.1 and things are going well.

EDIT: Things seem to be working well, it just took me a second to figure out I was using the wrong type of "required", the current version of the validator seems to like the http://json-schema.org/draft-03/schema spec as opposed to the latest draft-04 where they changed how they were doing required propertied.

**Comment by mirfilip** [comment]
This package is probably the most state-of-art json-schema validator in PHP valley. It would be **greatly appreciated** to have it stated what draft version is supported, along with implemented/missing features table. You know, just to avoid people adding issues that you know isn't there and to avoid them being caught up in the middle of developing the schema, just because they meet this missing feature.

**Comment by bighappyface** [comment]
@mirfilip if we base the support listing on what JSON Schema Test Suite files are *not* being skipped then we are nearly there for Draft 3 and Draft 4.

We can open a PR and add a feature support table in the README to make it clear on the repo home page what is or is not supported.

**Comment by mirfilip** [comment]
@bighappyface Right. I will prepare some kind of table. Maybe sphinx based docs would be cool. I will also go through the skipped suites and double check if there are no false positives etc.
