### ISSUE TITLE
Not throwing error for inner items of associative array

### ISSUE THREAD

**Issue by Somebi** [justinrainbow/json-schema#296]
```
$data=json_decode(json_encode(array(
    "inner1" => array("foo" => array("id_1232" => "blah"))
)));

$refResolver = new JsonSchema\RefResolver(new JsonSchema\Uri\UriRetriever(), new JsonSchema\Uri\UriResolver());
$schema = $refResolver->resolve('file://' . realpath('schema.json'));
$validator = new JsonSchema\Validator();
$validator->check($data, $schema);
var_dump($validator->isValid());
```

Schema:

```
{
	"title": "Lobby data schema",
	"type": "object",
	"properties": {
		"inner1": {
			"type": "object",
			"items": {
				"type": "object",
				"properties": { 
					"foo": {
						"type": "string"
					}
				},
				"required": ["foo"]
			}
		}
	},
	"required": ["inner1"]
}
```

How to validate php associative array with array inside it?

**Comment by FlorianSW** [comment]
Your JSON schema doesn't reflect what you want to do. Let's do a quick, but hopefully deep analysis :D

* The top level element needs to be an object: checked, as the php `array( "key" => "value" )` encodes to an object in JSON.
* the object is allowed to have the following properties (as indicated by the `properties` key):
** `inner1` -> checked, as the php `array( 'inner1' => 'bla' )` encodes to the json object `{ "inner1": "bla" }`
** ok, the `inner1` object is allowed to have the following listed items. Whoops? `items`? According to [the specification for a json schema](http://json-schema.org/latest/json-schema-validation.html#anchor36), `items` is a validation keyword for arrays, not for objects. So, the entirely `items` section of your json schema is correctly ignored for the object (as it's not an array). That's why (because `additionalProperties` isn't set to false), any value is valid against the given schema.

So, to fiy the problem, you should get rid of the `items` section and correctly represent your expected `properties` for the `inner1` object with the `properties` validation keyword. To achieve what you want, you could use this schema:
````
{
    "title": "Lobby data schema",
    "type": "object",
    "properties": {
        "inner1": {
            "type": "object",
            "properties": {
                "foo": {
                    "type": "string"
                }
            },
            "required": ["foo"]
        }
    },
    "required": ["inner1"]
}
````
Any value of `foo` is invalid, except strings.

Thanks for reporting this issue, but it seems to be invalid :-)

**Comment by bighappyface** [comment]
@FlorianSW thanks for jumping on this!

Closing... please re-open if necessary.
