### ISSUE TITLE
Tag 2.0.6

### ISSUE THREAD

**Issue by thewilkybarkid** [justinrainbow/json-schema#305]
Would it be possible to tag ef13b9b94ce3add40447cb454e511488fefaabe7 as `v2.0.6` so that #290 is available? It'll take a little while for other libraries to catch up to version 3.

**Comment by bighappyface** [comment]
@thewilkybarkid if you would do me a favor and ensure that commits u to and including ef13b9b are fully backward-compatible with 2.x.x then I would be happy to.

**Comment by thewilkybarkid** [comment]
The only BC break I can see is the type declaration changes in #276...

**Comment by bighappyface** [comment]
@thewilkybarkid thanks for the review.

I am going to leave the tags as they are. I understand that some consumers may not be able to get to 3.x.x very soon, but I believe a BC issue puts them at greater risk than excluding them from a feature. When we have introduced BC issues in the past, it hasn't turned out well.

Again, thanks for the review, your assistance, and your understanding.
