### ISSUE TITLE
Validator object appears to keep its validation status

### ISSUE THREAD

**Issue by CMCDragonkai** [justinrainbow/json-schema#385]
I'm using 5.1 version.

```php
<?php

use JsonSchema\Validator;

$validator = new Validator;

$data = (object)['key' => true];

$validator->validate(
    $data,
    (object)[
        'type' => 'object',
        'properties' => (object)[
            'key' => (object)[
                'type' => 'boolean'
            ]
        ]
    ]
);

var_dump($validator->isValid()); // true

$data = ['key' => true];

$validator->validate(
    $data,
    (object)[
        'type' => 'object',
        'properties' => (object)[
            'key' => (object)[
                'type' => 'boolean'
            ]
        ]
    ]
);

var_dump($validator->isValid()); // false


$data = (object)['key' => true];

$validator->validate(
    $data,
    (object)[
        'type' => 'object',
        'properties' => (object)[
            'key' => (object)[
                'type' => 'boolean'
            ]
        ]
    ]
);

var_dump($validator->isValid()); // false but should be true
```

There should be a way to clear the Validator status? Or that subsequent invocations of validate should not keep the original validation status.

**Comment by erayd** [comment]
@CMCDragonkai Thanks for letting us know - will take a look now, stand by.

**Comment by erayd** [comment]
@CMCDragonkai It's already possible to reset the validation status - just use `Validator::reset()`:
```PHP
<?php

use JsonSchema\Validator;

require('vendor/autoload.php');
$v = new Validator();

$validSchema = json_decode('{"type":"string"}');
$invalidSchema = json_decode('{"type":"object"}');
$data = json_decode('"ABC"');

$v->validate($data, $invalidSchema);
assert(!$v->isValid());

$v->reset(); // This line resets isValid

$v->validate($data, $validSchema);
assert($v->isValid());
```

For the sake of usability, I have added this call in PR #386 , which will allow object reuse without needing to manually reset it.

**Comment by bighappyface** [comment]
See #390 - The built-in reset will be official in 6.0.0

**Comment by bighappyface** [comment]
PRs welcome

**Comment by erayd** [comment]
@aboyton The main problem is that this project is woefully short of manpower, and contains a massive amount of legacy code that dates to well before any of us were involved with it. There aren't many active contributors, and none of us have much time available. In order to update the documentation, somebody would need to commit the time to do it. It's on my list, but there are other things that are higher priority than writing documentation for 5.x, and I don't have much time available at present.

As @bighappyface mentioned above, PRs are always welcome - if you would like to submit documentation for 5.x, we'd love to have it. Otherwise, regrettably, there will be something of a wait.

In the meantime, if you have specific questions, please feel free to ask, and I'll do my best to assist you. I'm very aware that the documentation is significantly lacking. You may also wish to refer to #440 - this PR is a work in progress that adds better PHPDoc comments to the public API. It's only partly complete, but hopefully it helps a little in the interim.

**Comment by aboyton** [comment]
Sorry I realised that I never replied to this nor made a pull request. Thanks for your work on this, I've made a small pull request with a sentence added for calling `reset`.
