### ISSUE TITLE
phpunit dependency prevents install 

### ISSUE THREAD

**Issue by stefgosselin** [justinrainbow/json-schema#412]
Hi, 

When bundling this library with symfony based framework, composer dependency resolution fails because of outdated phpunit version.

`Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - composer/composer 1.3.3 requires justinrainbow/json-schema ^1.6 || ^2.0 || ^3.0 || ^4.0 -> satisfiable by justinrainbow/json-schema[1.6.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 3.0.0, 3.0.1, 4.0.0, 4.0.1, 4.1.0, v1.6.0] but these conflict with your requirements or minimum-stability.
    - composer/composer 1.3.3 requires justinrainbow/json-schema ^1.6 || ^2.0 || ^3.0 || ^4.0 -> satisfiable by justinrainbow/json-schema[1.6.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 3.0.0, 3.0.1, 4.0.0, 4.0.1, 4.1.0, v1.6.0] but these conflict with your requirements or minimum-stability.
    - Installation request for composer/composer (locked at 1.3.3) -> satisfiable by composer/composer[1.3.3].

`

Would it be possible to bump up phpunit dependency version? 

Or remove the phpunit dependency?

BTW -> phpunit is now past 7.0.0 release.

**Comment by erayd** [comment]
I'm aware it's ancient, but unfortunately we cannot bump the PHPUnit dependency due to the requirement for PHP-5.3 support. PHPUnit 4.8 is the most recent release branch that is available for PHP-5.3.

Could you please clarify your issue, and why you think our PHPUnit version is causing the problem? PHPUnit is a dev dependency only; it's not required if you wish to use this library as a dependency of something else. This library has no runtime dependencies other than PHP itself, and (for 6.0.0 only) marc-mabe/php-enum.

**Comment by erayd** [comment]
I've done some further investigation, and it looks like the cause of the problem you have posted the log for is actually the old composer version - I'm not seeing any issues with PHPUnit. Composer-1.3.3 only supports up to v4.1.0 of this library, however the current stable release is v5.2.0.

If you bump your composer version to ^1.4, then it will resolve dependencies successfully, as that version of composer is compatible with our current stable release.

This works fine:
```JSON
{
    "require": {
        "symfony/symfony": "^3.2",
        "composer/composer": "^1.4",
        "justinrainbow/json-schema": "^5.2"
    }
}
```

If you still believe the problem lies with our PHPUnit dev-time dependency, could you please provide further information on why you think this is the case?

**Comment by erayd** [comment]
@stefgosselin Can this issue be closed?

**Comment by stefgosselin** [comment]
Yes Eyrad.  Sorry for not getting back to you sooner,  you have been most helpful, I appreciate
