### ISSUE TITLE
Only allow properties that are declared in JSON schema

### ISSUE THREAD

**Issue by sp-daniel-pinyol** [justinrainbow/json-schema#502]
Hi,
is there any way to only  allow properties that are declared in JSON schema, without having to specify additionalProperties for each one?
See https://stackoverflow.com/questions/17530762/only-allow-properties-that-are-declared-in-json-schema

thanks

**Comment by erayd** [comment]
No. The JSON-Schema spec doesn't have any mechanism for this other than `”additionalProperties: false`. However, there will probably be a new keyword to handle this situation when draft-08 of the spec is released.

**Comment by sp-daniel-pinyol** [comment]
thank you!

**Comment by shmax** [comment]
@erayd I can see where he's coming from. All but one or two of the 100+ endpoints in my own code base set `additionalProperties` to `false`, and I often forget to add the property. Sometimes I wish I could just configure my validator to assume `false` by default unless explicitly configured otherwise. Is there anything there?

**Comment by erayd** [comment]
@shmax The new keyword in draft-08 should allow you to do that. But draft-08 isn't released yet.

**Comment by shmax** [comment]
Right on, thanks!
