### ISSUE TITLE
Support for "const"?

### ISSUE THREAD

**Issue by martin-helmich** [justinrainbow/json-schema#506]
I just noticed that the `Validator` class does not appear to support the `const` keyword as specified in [section 6.1.3](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.3) of the spec. Is this intentional?

Given a few pointers where to start, I'd also be prepared to open a PR to add support for this feature.

```
$schema = [
        "properties" => [
                "foo" => [
                        "type" => "string",
                        "const" => "foo"
                ]
        ]
];

$doc = ["foo" => "bar"];

$validator = new JsonSchema\Validator();
$validator->validate($doc, $schema);

// expected: false, actual: true
var_dump($validator->isValid());
```

**Comment by erayd** [comment]
This validator currently doesn't support past draft-04, and const is a draft-06 keyword (mainly because this project lacks resources - not enough devs, and those of us who do work on it don't have tons of available time, and I'm also maintaining another validator too). I'm intending to bring this project up to scratch with the newer standards at some point (probably after draft-08 is released, because that version may require some significant architectural changes), but if you'd like to open a PR for const support earlier, we'd love to have your contribution to the project :-).

**Comment by martin-helmich** [comment]
@erayd Thanks for the feedback! I've opened a pull request at #507.
