### ISSUE TITLE
Cache remote schema with external $refs

### ISSUE THREAD

**Issue by gianbasagre** [justinrainbow/json-schema#529]
Is it possible to cache a remote schema that uses external $refs? I'm thinking of the ability to get a serialized versione of the remote schema with all the external $refs resolved, then the ability to add it later to the schema storage?

**Comment by erayd** [comment]
Yes. The library doesn't have a native caching mechanism, but there is nothing stopping you from caching it yourself and supplying it to the library directly.

**Comment by erayd** [comment]
Note that if you do this, you'll also need to deal with `$ref` yourself also. The library cannot provide you with a dereferenced version of a schema, because fully dereferencing can result in infinite recursion, and is thus impossible (e.g. if a subschema contains a reference to its own ancestor). As such, this library uses a 'lazy dereferencing' model, and dereferences things as they are needed during validation.

Don't ever attempt complete dereferencing of an untrusted schema unless you also have some kind of mechanism to prevent infinite recursion. Infinitely recursing is in violation of the JSON schema spec, and is also a great denial of service vector.
