### ISSUE TITLE
Getting Resolved Schema as a string

### ISSUE THREAD

**Issue by beschoenen** [justinrainbow/json-schema#532]
I have a few JSON schemas with references to other files that I want to expose via an API.
I want the API to return a single file with the references resolved.

Is it possible to resolve the references of a schema and get the resulting schema as a JSON object?

**Comment by erayd** [comment]
No, this isn't possible. Recursive schemas cannot be fully resolved - the expanded form of a recursive schema is infinite. As such, this library dereferences schemas on an 'on demand' basis, where the reference is required in order to validate a document instance.

If it's essential that you have a single file, you will need to write your own pre-processor to do this, but please be aware of the recursion caveat - if you are accepting untrusted schemas, then you will need some mechanism to error out when infinite recursion is encountered.

**Comment by beschoenen** [comment]
Ok, thank you for the information.
