### ISSUE TITLE
Ability to disable media type validation for UriRetriever

### ISSUE THREAD

**Issue by estahn** [justinrainbow/json-schema#543]
There are several endpoints that do not have the correct media type (e.g. http://json-schema.org/). While this is not ideal it's current reality.

It would be great to be able to disable the content type check as we don't have control of upstream schemas.

Same as #540

**Comment by erayd** [comment]
This is a good idea. It shouldn't be the default behavior, but adding a config flag to allow non-compliant mimetypes would be extremely helpful to those for whom fixing the mimetype header isn't a viable option.

PRs are welcome, or otherwise I'll get to it eventually :-). We're fairly short on manpower on this project.
