### ISSUE TITLE
icecave/parity dependency concern

### ISSUE THREAD

**Issue by wimleers** [justinrainbow/json-schema#570]
In the `master` branch, #518 added a dependency on `icecave/parity`. That in turn has a dependency on `icecave/repr`. Per https://github.com/IcecaveStudios/parity/issues/15#issuecomment-469437681, Drupal core maintainers [do not want to add](https://www.drupal.org/project/drupal/issues/3036210#comment-13000014) `icecave/*` dependencies to Drupal core.

(The `5.2.x` releases don't contain the `icecave/*` dependencies, but if Drupal needs to update to a release based that contains #518, it'd become a problem at that point.)

Would you be willing to use an alternative approach that does not depend on that library?

P.S.: this is related to https://github.com/justinrainbow/json-schema/issues/569, and thanks for your prompt response there!

**Comment by shmax** [comment]
@wimleers 

Just so I understand, which part of his response was it that raised red flags? He said that most of his packages don't see active development, but he also seems open to fixes, so before I go off and find a replacement it might save me some time if I know exactly what it is I should be looking for...

**Comment by shmax** [comment]
To put it another way, if you're concerned about maintenance on `icecave/parity`, wouldn't it make more sense to look for a replacement if/when it actually becomes an issue?

**Comment by xjm** [comment]
Thanks @shmax for the prompt response!

For us it is about predictability, future compatibility, and risk mitigation. Let's say the next major version of `json-schema` is released, and then six months later Icecave EOLs their package as they've indicated is going to happen at some point. Then the choices are:

- Proceeding with an unsupported package that won't receive security coverage.
- Forking the package.
- A BC break.
- A new major version with whatever replacement.

All of the above are variously disruptive or risky for a package with a need for scheduled releases and LTS support.

**Comment by erayd** [comment]
@xjm That makes sense. Noting the way we use parity, the dependency could likely be removed.

**Comment by shmax** [comment]
Well, sure, we could probably factor it out or replace it, but if I spent all my time trying to second guess which projects are going to EOL in six months and proactively replacing them I wouldn't get much done (this project isn't exactly a hotbed of activity, either). We use this package at one place in the code, and it hasn't been an issue since I put it in. So barring some unforeseen future complication, if they EOL it won't make any difference to us. And if there *is* some complication, then we can fix it then. We have 56 open issues now--many of which document real bugs--so it seems a little bizarre to me to focus on this as some kind of blocker. Hell, we could just revert the commit and go back to having 57 open issues instead of 56. *shrug*

**Comment by DannyvdSluijs** [comment]
@wimleers in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is an issue which time has caught up on? The `icecave/parity` [[link]](https://github.com/icecave/parity) repo seems to be inactive but the code is there and over time it even has grown to a version 3 whereas this repo still is set on version 1. I see your concerns and I think they are valid up to a point, but functionally there is currently no impact on the library.
So my remaining question is can this issue be closed? Feel free to close it yourself with some comments if helpful.

**Comment by alcalyn** [comment]
Hi, we had to use version 5.3 instead of 6 of this package because version 6 introduces `icecave/parity =1.0.0`, which requires `icecave/repr ~1`, which breaks on newer versions of php because of this syntax:

https://github.com/icecave/repr/blob/1.0.1/src/Generator.php#L229

The commit of the tag v6 has been done 6 years ago so I understand about using version 1 at this time, but the tag v6 has been released 3 weeks ago (which was surprising to me).

**Comment by DannyvdSluijs** [comment]
> Hi, we had to use version 5.3 instead of 6 of this package because version 6 introduces `icecave/parity =1.0.0`, which requires `icecave/repr ~1`, which breaks on newer versions of php because of this syntax:
> 
> https://github.com/icecave/repr/blob/1.0.1/src/Generator.php#L229
> 
> (fixed in 2.0.1)
> 
> The commit of the tag v6 has been done 6 years ago so I understand about using version 1 at this time, but the tag v6 has been released 3 weeks ago (which was surprising to me).

Hi @alcalyn 

thanks for you comment. If you think this is something needed fixing you could best open a new issue. It would be a great timesaver if you can provide more details on how to reproduce. 

Mainly the PHP version is important. Version 6.0 still supports PHP 5.3 (which is probably why it was pinned in such a way). Work is being done to get version 6.1 done with the main feature to support PHP 7.2 and up and fix any issues with PHP 8.0 and greater.

**Comment by shirshir** [comment]
Unfortunately I was also unable to upgrade to v6 because of `icecave/parity:1.0.0`. This dependency triggered a couple of vulnerability warnings for the `twig/twig:v1.15` [sub dependency](https://github.com/icecave/parity/blob/1.0.0/composer.lock#L1064-L1065):

[CVE-2015-7809](https://github.com/advisories/GHSA-xw83-pwrm-9j74)
[CVE-2022-39261](https://github.com/advisories/GHSA-52m2-vc4m-jj33)
[CVE-2019-9942](https://github.com/advisories/GHSA-vxrc-68xx-x48g)
