### ISSUE TITLE
propertyNames, patternProperties do not work v2

### ISSUE THREAD

**Issue by BlackFireTME3C** [justinrainbow/json-schema#573]
This bug is resolved https://github.com/justinrainbow/json-schema/issues/36 but it seems it does not work properly.

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://json-schema.org/draft-07/schema#",
  "title": "Schema",
  "type": "object",
  "propertyNames": {
    "$ref": "#/definitions/localeIdentifier"
  },
  "patternProperties": {
    "": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/localeIdentifier"
      }
    }
  },
  "definitions": {
    "localeIdentifier": {
      "type": "string",
      "maxLength": 2,
      "minLength": 2
    }
  }
}
```

Test data:

```
{"abc":["ab"]} // works
{"ab":["abc"]} // works
```

This 2 examples should fail.

**Comment by piotrkochan** [comment]
It looks like propertyNames constraint is not supported and patternProperties works only when pattern is defined (eg ".*") but it still should work with empty value.

**Comment by erayd** [comment]
This library does not support draft-07, but your schema requires some newer features in order to function properly. The latest version of the spec that is fully supported by this library is draft-04. Unfortunately, this does mean that I'm going to close this issue without a fix in place.

You are welcome to submit a PR implementing this functionality - we are extremely short of manpower on this project, so any useful contributions to the codebase are greatly appreciated.

**Comment by erayd** [comment]
@piotrkochan An empty key for `patternProperties` is not valid. ECMA-262 states that a regular expression literal (which the key must be) may not be empty.

**Comment by piotrkochan** [comment]
Still it does not work even for patterns like:

```"patternProperties": {
    "^[A-Z]{2}+$": {
```

**Comment by erayd** [comment]
@piotrkochan That looks like your example from #584. If so, this isn't working because your data does not match the pattern. That pattern will only match a string containing an even number of upper-case characters, but your test data was lower-case.

If you're saying that this isn't working with data that it should be matching, could you please post some example data here so that I can investigate further.
