### ISSUE TITLE
"bsonType" 

### ISSUE THREAD

**Issue by thawkins** [justinrainbow/json-schema#577]
Is it possible to extend the validator with the mongodb specific "type" data "bsontype" as shown on 

https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/#extensions

This would allow validation of records read from mongodb databases.

**Comment by erayd** [comment]
We will never merge such a change here, because it's completely outside of the spec.

The type system in this library wasn't designed to be extensible, because JSON schema prescribes a very limited list of primitive types. It's doable, if you want to maintain your own fork - but note that it'll be somewhat annoying, as there are type assumptions etc. all over the place; it's not nicely centralised in one place.

**Comment by shmax** [comment]
It's too bad we don't have some kind of plugin system. That's how they tackled the `bsonType` situation over at AJV: https://github.com/BoLaMN/ajv-bsontype

That said, if @thawkins is determined, there's always the fact that virtually any of our constraint classes can be overridden and fed back into the system. I don't know how deep the `bsonType` rabbit hole goes, but it might be worth tinkering with.

**Comment by erayd** [comment]
@thawkins If you're really keen to do this, I'd be open to merging things here that simplify and / or modularise the type system, providing it remains spec-compliant and doesn't cause performance issues. That may make maintaining a `bsonType` fork or extension somewhat easier for you.

As @shmax says, our constraint classes are extensible, although the type system is not. But if you want to deal with `bsonType` as a completely independent custom keyword, that would be the place to start

**Comment by thawkins** [comment]
I will look at what is required
