### ISSUE TITLE
Question: Why does the schema have to be nested objects?

### ISSUE THREAD

**Issue by designermonkey** [justinrainbow/json-schema#637]
In the examples, the schema is cast t an object, as are all the internal properties of the schema. I use yaml to define my schemas, and use the `yaml_parse` function provided by the pecl yaml extension, so the data I get back is nested arrays, not objects.

It's laborious to go through this to convert arrays to objects.

Is there really a need for it to all be nested objects?

**Comment by erayd** [comment]
Because JSON schemas are defined in the spec as objects, this library ingests and processes them as such. There is no such thing as an associative array type in JSON.

If you're decoding a schema into an associative array, then you are introducing a completely foreign type into the process (with some related loss of fidelity along the way). It's simply not a valid thing to do.
