### ISSUE TITLE
definitions/ref resolving

### ISSUE THREAD

**Issue by vpArth** [justinrainbow/json-schema#638]
I have an issue with inline schema references.

Minimal sample:

```php
<?php

use JsonSchema\Constraints\Factory;
use JsonSchema\SchemaStorage;
use JsonSchema\Validator;

require_once './vendor/autoload.php';

$schemaJson = <<<'JSON'
{
 "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "a": {
      "$id": "#a",
      "type": "string"
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "$ref": "#a"
    }
  }
}
JSON;


$schema  = json_decode($schemaJson, false);
$storage = new SchemaStorage();
$storage->addSchema(SchemaStorage::INTERNAL_PROVIDED_SCHEMA_URI, $schema);
$validator = new Validator(new Factory($storage));

$sample = json_decode('{"name": "Smith"}', false);

$validator->validate($sample, $schema);
// JsonSchema\Exception\ResourceNotFoundException: JSON schema not found at file:///home/arth/sample/ in /home/arth/sample/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/Retrievers/FileGetContents.php on line 48

assert($validator->isValid(), json_encode($validator->getErrors()));
```

If I set `"type": "string"` instead of `$ref: "#a"`, all ok

What am I doing wrong? Why reference to $id cause external files retrieve attemptions?

**Comment by erayd** [comment]
So, a couple of points there.

1. While `$id` is valid in draft-07, this library doesn't yet support that version of the spec. In draft-04, which *is* supported, the correct keyword is `id`.

2. This library doesn't support inline dereferencing, which is optional as per the spec (see [draft-04 core section 7.2.3](https://tools.ietf.org/html/draft-zyp-json-schema-04#section-7.2.3)). What you are trying to do cannot be done without inline dereferencing.

If you change your reference to use `"$ref": "#/definitions/a"` instead of the defined ID, then this can be resolved correctly using canonical dereferencing. While probably not the outcome you were hoping for, it is at least a valid workaround that will allow your schema to work properly with this library.

If you would like to contribute a PR that implements inline dereferencing, you are welcome to do so. Otherwise, it's probably unlikely to happen any time in the near future sorry; this project simply doesn't have the developer time available to implement it.

**Comment by vpArth** [comment]
I can not to modify the schema, but anyway, thank you for clarifying.

**Comment by erayd** [comment]
> I can not to modify the schema...

What about changing the value prior to processing? If you do this after decoding, it will have the same effect:

```php
$schema  = json_decode($schemaJson, false);
$schema->properties->name->{'$ref'} = '#/definitions/a';
$storage->addSchema(SchemaStorage::INTERNAL_PROVIDED_SCHEMA_URI, $schema);
...
```

If you need to do this in multiple places, it can be achieved via recursive preprocessing. First scan the entire tree for IDs, and make note of the parts. Then scan the entire tree again, and replace any ref to those IDs as you go.
