### ISSUE TITLE
Unable to validate array type parameter with style option "Form"

### ISSUE THREAD

**Issue by damiendiels** [justinrainbow/json-schema#651]
I cannot find the way to validate  serializable parameter with the style form explode false. Maybe I missed something ?

**Comment by erayd** [comment]
Can you please clarify your problem? I don't understand your message.

If you could provide an example, that would be helpful.

**Comment by damiendiels** [comment]
I 've this parameter definition in my openapi.yaml file
`parameters:
    ArticleEmbed:
      description: Embed relationship
      name: _embed
      in: query
      style: form
      explode: true
      schema:
        type: array
        items:
          enum:
            - blocks
            - category
            - template
      examples:
        blocks:
          summary: Embed blocks
          value:
            - blocks
        category:
          summary: Embed category
          value:
            - category
        template:
          summary: Embed template
          value:
            - template`

Based on this openapi v3 specifications :[https://swagger.io/docs/specification/serialization/]( https://swagger.io/docs/specification/serialization/)

I want to validate the parameter like this :
` $validator->validate($data, $jsonSchema, Constraint::CHECK_MODE_TYPE_CAST);` 
I 've tried all the Constraint check mode without succes.

Result is allways the same : 
eg : 
for this request  : /articles/:id?_embed=template,category
`
array:1 [
  0 => array:5 [
    "property" => ""
    "pointer" => ""
    "message" => "String value found, but an array is required"
    "constraint" => "type"
    "context" => 1
  ]
`

**Comment by erayd** [comment]
That looks like user error.

Swagger and JSON schema are not the same thing, however looking at your example, your schema is requiring an array for that parameter, but your data contains a string instead. And the validation is (correctly) failing because of that.

For the avoidance of doubt, please note that you cannot automatically coerce a string into an array. If you wish to validate it as an array, then you'll need to ensure that you are actually passing an array to the validator.

**Comment by damiendiels** [comment]
Ok thank you ! That's what I thought.
