### ISSUE TITLE
Validation always returning true

### ISSUE THREAD

**Issue by mmendescortes** [justinrainbow/json-schema#683]
The following always return true when `$validator->isValid()` is called, even with other schema and json the result is always true. Please help me, I need this validation to work. Is there a version of this library where it works fine?
```
            $validation = $validator->validate(json_decode(<<<'JSON'
                {
                    "isUser": true,
                    "isModerator": false
                }
            JSON), json_decode(<<<'JSON'
                {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "required": ["isModerator", "isUser", "sent_at"],
                    "definitions": {
                        "isModerator": {
                            "type": "boolean",
                            "default": false
                        },
                        "isUser": {
                            "type": "boolean",
                            "default": false
                        },
                        "sent_at": {
                            "type": "integer"
                        },
                    }
                }
            JSON));
```

**Comment by erayd** [comment]
Your schema is invalid JSON - it contains a trailing comma after the `sent_at` object, and thus does not parse. As a result, you are trying to validate the data against a null schema, which is the same as validating it against no constraints at all (and thus, validation passes, because no constraints are violated). If you remove the comma, then your schema will parse correctly.

There are also two additional problems:

1. You are passing a value for the data argument, rather than a variable. This will cause problems, as literals cannot be passed as a reference, and the validator requires a reference. Please decode the JSON into a variable, then pass the variable to `$validate->validate()`.
2. Your schema does nothing but require the properties `isModerator`, `isUser` and `sent_at` to be present. `definitions` is a container keyword intended to hold schema fragments that can be used elsewhere, but does not enforce anything. You probably want to be using the `properties` keyword there, not `definitions`.

**Comment by mmendescortes** [comment]
> Your schema is invalid JSON - it contains a trailing comma after the `sent_at` object, and thus does not parse. As a result, you are trying to validate the data against a null schema, which is the same as validating it against no constraints at all (and thus, validation passes, because no constraints are violated). If you remove the comma, then your schema will parse correctly.
> 
> There are also two additional problems:
> 
> 1. You are passing a value for the data argument, rather than a variable. This will cause problems, as literals cannot be passed as a reference, and the validator requires a reference. Please decode the JSON into a variable, then pass the variable to `$validate->validate()`.
> 2. Your schema does nothing but require the properties `isModerator`, `isUser` and `sent_at` to be present. `definitions` is a container keyword intended to hold schema fragments that can be used elsewhere, but does not enforce anything. You probably want to be using the `properties` keyword there, not `definitions`.

Thank you very much for your help! I will be doing as told.

**Comment by mmendescortes** [comment]
Still having problems with this validation when $parsedMessage is an empty array or anything else at all...

I decided to post the entire code instead of only a chunk, so if you can help me get it working I would be very grateful.

```
                $validation = $validator->validate($parsedMessage, json_decode(<<<'JSON'
                    {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "required": ["visitorId", "username", "message", "isModerator", "isUser", "toApprove", "approved", "sent_at"],
                        "properties": {
                            "id": {
                                "type": "integer",
                            },
                            "visitorId": {
                                "type": "string",
                            },
                            "username": {
                                "type": "string",
                                "minimum": 1
                            },
                            "message": {
                                "type": "string",
                                "minimum": 1
                            },
                            "isModerator": {
                                "type": "boolean",
                                "default": false
                            },
                            "isUser": {
                                "type": "boolean",
                                "default": false
                            },
                            "toApprove": {
                                "type": "boolean",
                                "default": true
                            },
                            "approved": {
                                "type": "boolean",
                                "default": false
                            },
                            "sent_at": {
                                "type": "integer"
                            }
                        }
                    }
                JSON));
```

**Comment by erayd** [comment]
> Still having problems with this validation when $parsedMessage is an empty array or anything else at all...

That is because your schema actually *allows* empty arrays etc. Anything that is not an object is considered valid according to your schema, because the `required` and `properties` constraints apply exclusively to objects, and you do not have a `type` constraint (so any data type is allowed).

I get the impression that you are not familiar with JSON Schema - I strongly advise you to read the [draft 4 standard](https://json-schema.org/specification-links.html#draft-4), which describes the version of JSON Schema that is implemented by the 5.x.x (stable) branch of this library.
